name: Maven Deploy

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Replace Maven Credentials
      run: |
        sed -i 's/USERNAME/${{ secrets.USERNAME }}/g' .github/settings.xml
        sed -i 's/PASSWORD/${{ secrets.PASSWORD }}/g' .github/settings.xml

    - name: Install
      run: ./mvnw clean -U install -X -s .github/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.github.token }}
    - name: Docker build
      run: docker build -t my-image .
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Login to Azure Container Registry
      run: az acr login --name oskaksdemo
    - name: Docker tag
      run: docker tag my-image oskaksdemo.azurecr.io/my-image:latest
    - name: Docker push
      run: docker push oskaksdemo.azurecr.io/my-image:latest
  deploy:
    needs: build
    runs-on: arc-runner-demo
    steps:
    - uses: actions/checkout@v3
    - name: Install azure-cli
      uses: pietrobolcato/install-azure-cli-action@v1.0.1    
    - name: Login to Azure
      uses: azure/login@v1.6.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/setup-kubectl@v4.0.0
    - name: Configure kubectl
      run: az aks get-credentials --resource-group rg-sonarqube-demo --name osk-aks-demo
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
