name: Maven Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3

    - uses: jessehouwing/actions-semver-checker@v1
      with:
        check-minor-version: true
