name: Maven Build with Sonarqube

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: arc-runner-demo

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Install Apache Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Replace Maven Credentials
      run: |
        sed -i 's/USERNAME/${{ secrets.USERNAME }}/g' .github/settings.xml
        sed -i 's/PASSWORD/${{ secrets.PASSWORD }}/g' .github/settings.xml

    - name: Install
      run: ./mvnw clean -U install -X -s .github/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.github.token }}
    
    - name: Extract JAR file version
      id: extract_version
      run: echo "JAR_FILE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=medium-demo -Dsonar.projectName='medium-demo'